getUnits
blizzhackers/Charon pull request #10
Opened 2020-10-01 19:24 UTC by jaenster

2020-10-02 02:16 UTC, Nishimura-Katsuo commented
Can you switch this to use std::vector instead of std::list? It's more performant in all the categories I personally care about, including push_back.

https://dzone.com/articles/c-benchmark-%E2%80%93-stdvector-vs

2020-10-02 02:20 UTC, Nishimura-Katsuo requested changes
Change this to use std::vector instead of std::list. For vectors push_back and linear search (including iteration) is going to be faster because of how memory is cached.

https://dzone.com/articles/c-benchmark-%E2%80%93-stdvector-vs

2020-10-09 19:02 UTC, jaenster commented
Sorry, took a while

2020-10-09 19:23 UTC, dzik87 approved these changes

2020-10-09 19:40 UTC, Nishimura-Katsuo requested changes

2020-10-09 19:40 UTC, Nishimura-Katsuo commented on framework/utilities.cpp
> +            if (unit->dwType == type) {
this check isn't needed because you're already checking the hash table by type

2020-10-09 19:40 UTC, Nishimura-Katsuo commented on framework/utilities.cpp
> +std::vector<D2::Types::UnitAny*> getUnits(int type) {
needs to accept the hash table as an argument (in case we're doing it server side with pGame instead of client side units)

2020-10-15 15:35 UTC, jaenster commented
Updated to requested changes

2020-10-15 15:44 UTC, closed without merging

2020-10-15 15:54 UTC, Nishimura-Katsuo commented
Webhook test.